language: node_js

node_js:
  - 7
  - 8
  - 9

script:
  - npm run lint

after_success: 'npm run coveralls'

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
